"""empty message

Revision ID: 094d8bd5614b
Revises: 7782e1b98e83
Create Date: 2021-01-21 14:43:04.931865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094d8bd5614b'
down_revision = '7782e1b98e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily', 'total_cases')
    op.drop_column('daily', 'total_recoveries')
    op.drop_column('daily', 'total_deaths')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily', sa.Column('total_deaths', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('daily', sa.Column('total_recoveries', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('daily', sa.Column('total_cases', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
