"""empty message

Revision ID: 4f5885c51237
Revises: 094d8bd5614b
Create Date: 2021-01-21 14:43:19.913656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5885c51237'
down_revision = '094d8bd5614b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily', sa.Column('total_cases', sa.Integer(), nullable=True))
    op.add_column('daily', sa.Column('total_deaths', sa.Integer(), nullable=True))
    op.add_column('daily', sa.Column('total_recoveries', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily', 'total_recoveries')
    op.drop_column('daily', 'total_deaths')
    op.drop_column('daily', 'total_cases')
    # ### end Alembic commands ###
