"""empty message

Revision ID: 6fbded67ecd8
Revises: 
Create Date: 2021-01-21 14:19:02.412616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbded67ecd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_cases', sa.String(), nullable=True),
    sa.Column('total_deaths', sa.String(), nullable=True),
    sa.Column('total_recoveries', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily')
    # ### end Alembic commands ###
