"""empty message

Revision ID: fa027832ec08
Revises: 
Create Date: 2021-01-20 18:29:37.878771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa027832ec08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('total_cases', sa.String(), nullable=True),
    sa.Column('total_deaths', sa.String(), nullable=True),
    sa.Column('total_recoveries', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily')
    # ### end Alembic commands ###
